### ISSUE TITLE
just simulate lidar?

### ISSUE THREAD

**Issue by jeannotes** [liuzuxin/Pesudo_Lidar_PointCloud_Carla#1]
hi, can this package be used to simulate lidar as well as get its semantic infomation? for example to get every point's class info.

**Comment by liuzuxin** [comment]
> hi, can this package be used to simulate lidar as well as get its semantic information? for example to get every point's class info.

Hi, this is an ongoing project and we haven't finished it... (Actually just started..) Yes, what you mentioned is exactly what we want to do.

**Comment by jeannotes** [comment]
希望能够多多交流哈，我最近也在做哈
